export enum ROLES {
  PENDING = "PENDING",
  STUDENT = "STUDENT",
  TEACHER = "TEACHER",
  STAFF = "STAFF",
  PRINCIPAL = "PRINCIPAL",
}

export enum STATUS {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
}

export enum APPROVE {
  APPROVED = "APPROVED",
  PENDING = "PENDING",
  NOT_APPROVE = "NOT_APPROVE",
  PENDING_PAYMENT = "PENDING_PAYMENT",
  DAPODIK_ISSUE = "DAPODIK_ISSUE",
  DATA_ISSUE = "DATA_ISSUE",
}
